<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PRIYA" failures="0" tests="4" name="Ethos.com.Test.StringCal_Test" time="0.006" errors="1" timestamp="2024-02-01T17:09:37 IST" skipped="0">
  <testcase classname="Ethos.com.Test.StringCal_Test" name="TestAddition" time="0.000">
    <error message="Negative Numbers Are Not Allowed" type="Ethos.com.Class.Negtive_Number_Exception">
      <![CDATA[Ethos.com.Class.Negtive_Number_Exception: Negative Numbers Are Not Allowed
at Ethos.com.Class.StringCal_logic_page.add(StringCal_logic_page.java:32)
at Ethos.com.Test.StringCal_Test.TestAddition(StringCal_Test.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TestAddition -->
  <system-out/>
  <testcase classname="Ethos.com.Test.StringCal_Test" name="TestAddition" time="0.005"/>
  <system-out/>
  <testcase classname="Ethos.com.Test.StringCal_Test" name="TestAddition" time="0.001"/>
  <system-out/>
  <testcase classname="Ethos.com.Test.StringCal_Test" name="TestAddition" time="0.000"/>
  <system-out/>
</testsuite> <!-- Ethos.com.Test.StringCal_Test -->
